### ISSUE TITLE
Filtering with Multiple File Type

### ISSUE THREAD

**Issue by omuomugin** [miguelpruivo/plugins_flutter_file_picker#114]
Hi, thanks for your great plugin.

Is there any way to filter file type like below?

```
getFilePath(type: FIleType.IMAGE || FileType.VIDEO || FileType.AUDIO);
```

I don't want to target drives and other cloud files but I want to target Image, video and audio.

**Comment by miguelpruivo** [comment]
Hi, right now you can achieve with the type `FileType.ALL` as it will let you pick any file. To provide a seamless experience between iOS and Android, it's hard to not say impossible, to let pick _video_, _images_. and _ audio_ at the same time because _audio_ will use the Music app to let you pick the files.

However, _image_ and _video_ together might be a possibility as it will open the gallery on iOS.

**Comment by omuomugin** [comment]
Ok, I can understand that.
I will insert some dialog to choose file type instead.

**Comment by miguelpruivo** [comment]
@omuomugin as of now, with version [1.6.0 released just now](https://pub.dev/packages/file_picker#160) you can start filtering multiple extensions at once. There are breaking changes, so have in mind that from now on you'll need to provide an `List` of file types instead of a single one with `FileType.custom`.

Example:
```
 List<File> files = await FilePicker.getMultiFile(
          type: FileType.custom,
          allowedExtensions: ['jpg', 'pdf', 'doc'],
        );
```
Thank you.

**Comment by omuomugin** [comment]
Thanks for the feature. It’s super cool :+1:
