### ISSUE TITLE
Add support for picking a directory

### ISSUE THREAD

**Issue by kinex** [miguelpruivo/plugins_flutter_file_picker#23]
Usage scenario: To export data from an app user must be able to select an output directory where to save the file. Tip for iOS implementation: see UIDocumentPickerMode.ExportToService

**Comment by kgamecarter** [comment]
Android implementation
[https://github.com/googlesamples/android-DirectorySelection](https://github.com/googlesamples/android-DirectorySelection)

**Comment by miguelpruivo** [comment]
This was actually wip to the current deployed version `1.3.0`, however, this should be more discussed as Android actually allows it but iOS don't. 

In iOS we usually either use the share capabilities to save/send some data or we use the app's data container to keep it. If we want to retrieve some directory it is possible but I believe that a concrete file pick is always required.

I was trying to avoid platform-specific features with this plugin and it's been already a tough task to fulfill because they differ fairly in the way they handle file picking. Nevertheless, I'm up to suggestions.

**Comment by rockgecko-development** [comment]
When I select a directory via `getMultiFilePath` via iCloud Drive, I get a folder containing `.<orig name>.icloud` files, of 175 bytes each.
I suppose this is because iCloud doesn't download the entire directory when you select it, unlike for individual files. But what do i do with these `.icloud` files, and how do I get the originals?

**Comment by miguelpruivo** [comment]
@rockgecko-development you are saying that you are able to select a folder when multi picking files?

**Comment by rockgecko-development** [comment]
@miguelpruivo yes.
Steps to reproduce:
iPhone 6, iOS 12
Call `getMultiFilePath` (it's not possible to select a folder in iCloud Drive with `getFilePath`)
Under *Locations*, choose iCloud Drive, then in the top bar press *Select*, which displays checkboxes for each item. Select a folder, then *Open*
In the result map, you get a folder which contains the `.<orig name>.icloud` placeholder files. Do you know what to do with these?

**Comment by miguelpruivo** [comment]
Thank you @rockgecko-development. Definitely I wasn’t expecting folders to be able to of being picked in iOS so that’s probably the issue.

I’ll certainly look forward this in a future update.

**Comment by miguelpruivo** [comment]
Moved to #99.
