### ISSUE TITLE
App crashes if use file_picker on iPhone 5c

### ISSUE THREAD

**Issue by woozbooz** [miguelpruivo/plugins_flutter_file_picker#45]
Hello.
I want to use file_picker plugin in my flutter application.
In my App i use following code:
`_filePath=await FilePicker.getFilePath(type: FileType.ANY, fileExtension: 'bin');`

On iPad 64 it works fine, but when i run my App on iPhone 5c (iOS 10.3.3) and
try to pick a file - my App crashes with error message in debug:
`Assertion failure in -[UIDocumentPickerViewController _commonInitWithCompletion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3600.9.1/UIDocumentPickerViewController.m:91
2019-03-10 16:37:08.613635+0200 Runner[373:23247] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application initializing document picker is missing the iCloud entitlement. Is com.apple.developer.icloud-container-identifiers set?'`

How can i fix it?

**Comment by miguelpruivo** [comment]
Hello,

Hum, I’m glad it happened to you. I forgot to restrict document picker (by file extension) to iOS 11 and above. That is only supported by those versions since the iCloud file explorer was only introduced in the iOS 11. You can’t use that option on iOS 10.

I’m releasing a version 1.3.0 that adds a few features to the plugin such picking multiple files at once and audio files from music library along with some other improvements. You can check it on beta branch as of now. I’ll make sure to prevent access to custom file extension on versions prior to iOS 11.

Thank you for your feedback.

Regards,
Miguel Ruivo

No dia 10/03/2019, às 14:53, woozbooz <notifications@github.com<mailto:notifications@github.com>> escreveu:


Hello.
I want to use file_picker plugin in my flutter application.
In my App i use following code:
_filePath=await FilePicker.getFilePath(type: FileType.ANY, fileExtension: 'bin');

On iPad 64 it works fine, but when i run my App on iPhone 5c (iOS 10.3.3) and
try to pick a file - my App crashes with error message in debug:
Assertion failure in -[UIDocumentPickerViewController _commonInitWithCompletion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3600.9.1/UIDocumentPickerViewController.m:91 2019-03-10 16:37:08.613635+0200 Runner[373:23247] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application initializing document picker is missing the iCloud entitlement. Is com.apple.developer.icloud-container-identifiers set?'

How can i fix it?

**Comment by miguelpruivo** [comment]
Hello again,

Forgot my last answer to your email. I was thinking about other error. Just make sure you have iCloud Documents capabilities active in your app. See the image attached.

[enter image description here]
Com os melhores cumprimentos,
Miguel Ruivo

No dia 10/03/2019, às 14:53, woozbooz <notifications@github.com<mailto:notifications@github.com>> escreveu:

Application initializing document picker is missing the iCloud entitlement.

**Comment by woozbooz** [comment]
Thank you for answer. Sorry, but i can't find no images attached in your letter.

**Comment by miguelpruivo** [comment]
Hi again,

Basically you need to be using an Apple Developer Program account to sign your app in order to enable CloudKit for your under iOS 11 apps as mentioned here: https://developer.apple.com/library/archive/documentation/DataManagement/Conceptual/CloudKitQuickStart/EnablingiCloudandConfiguringCloudKit/EnablingiCloudandConfiguringCloudKit.html

Then you should be able to access the file explorer as expected.
Probably to prevent this kind of issues might not be a bad idea to add it to the docs.

Thank you for your feedback.

Miguel Ruivo

No dia 10/03/2019, às 15:24, woozbooz <notifications@github.com<mailto:notifications@github.com>> escreveu:


Thank you for answer. Sorry, but i can't find no images attached in your letter.
