### ISSUE TITLE
Chose image from camera

### ISSUE THREAD

**Issue by xyzbilal** [miguelpruivo/plugins_flutter_file_picker#57]
Hi, 
this is not an issue but a need I think at least for me. I m using  file from camera and with new update its removed so I cant upgrade to latest version. its possible add it again. I dont want to additional package for this purpose. thanks.

**Comment by miguelpruivo** [comment]
Hi. I’m sorry , this was actually a feature request and removed intentionally because when you are publishing your app doesn’t make sense to have camera permissions enabled when you don’t need them. 

If you want to stick with the camera and file picker, just either use both `file_picker` and `image_picker` or use an older version such as 1.2.0 (`file_picker: 1.2.0`).

Thank you for your compreenhsion.
