### ISSUE TITLE
display a file instead of file path

### ISSUE THREAD

**Issue by aachan13** [miguelpruivo/plugins_flutter_file_picker#89]
Hello.. is it possible to display the file instead of the file path? ex: i want to display my picked pdf file..

**Comment by miguelpruivo** [comment]
@aacham13 it sure it will, if you use a plugin for displaying/opening for example, pdf files. 

It wouldn’t make sense at all to have all the file the possibilities in this plugin, because after all, it’s just a file picker. You do what you want afterwards with the file. 

For example, if you use [flutter_full_pdf_viewer](https://pub.dev/packages/flutter_full_pdf_viewer#-readme-tab-) it will open pdf files for the provided path that you can get with this `file_picker`.
